import pygame
from numpy import array

pygame.init()

"""
Main constants
"""
WINDOW_TITLE = "PySoccer"
FPS = 300
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = pygame.display.get_desktop_sizes()[1] # type: ignore[attr-defined]

SPACE_DAMPING = 0.4        # Objects will loose 60% of their velocity per second
SPACE_COLLISION_SLOP = 0.2 # Object overlapping, higher value = better simulation stability

COLLISION_TYPE_PLAYER = 1
COLLISION_TYPE_BALL = 2
COLLISION_TYPE_WALL = 3
COLLISION_TYPE_GOAL_POST = 4
COLLISION_TYPE_GOAL_NET = 5

TEAM_BLUE = 1
TEAM_RED = 2

"""
Goal constants
"""
GOAL_SIZE = GOAL_WIDTH, GOAL_HEIGHT = 150, 350
GOAL_POST_RADIUS = 5
GOAL_POST_BORDER_GAP = 10
GOAL_NET_THICKNESS = 0.7
GOAL_NET_DENSITY = (10, 25)
GOAL_NET_NONCOLLISION_LAYERS = 9

"""
Player constants
"""
PLAYER_RADIUS = 25
PLAYER_WALKING_SPEED = 40
PLAYER_SPRINT_DURATION = 3000
PLAYER_SPRINT_FACTOR = 2
PLAYER_APPROX_MAX_SPEED = 300 # Helper constant used in scaling the kick force

KICK_MAX_FORCE = 1000         # Maximal kick force value
KICK_MIN_FORCE_FACTOR = 0.3   # Smallest kick force value is at 30% of maximal kick force value
KICK_MIN_DISTANCE_VALUE = 10  # Minimal distance from player to the ball allowed to perform a kick

"""
Ball constants
"""
BALL_RADIUS = 25

"""
Soccer field constants
"""
GRASS_TILE_SIZE = GRASS_TILE_WIDTH, GRASS_TILE_HEIGHT = 200, 200
WALL_THICKNESS = 5
FIELD_CIRCLE_RADIUS = SCREEN_HEIGHT / 5
FIELD_LINE_WIDTH = 3

"""
UI constants
"""
UI_BUTTON_SIZE = UI_BUTTON_WIDTH, UI_BUTTON_HEIGHT = 200, 50
UI_BUTTON_COUNT = 2
UI_BUTTON_DISTANCE = 20

"""
AI constants
"""
GK_MIN_APPROACH_DISTANCE = 80
GK_MAX_GOAL_DISTANCE = GOAL_WIDTH + GK_MIN_APPROACH_DISTANCE
GK_STARTPOS_GOAL_GAP = 30

"""
Linear algebra constants
"""
UNIT_X, UNIT_Y = array([1., 0.]), array([0., 1.])

# Computed constants
PLAYER_SPRINT_MAX_ENERGY = PLAYER_SPRINT_DURATION * FPS
PLAYER_SPRINT_ENERGY_DROP = PLAYER_SPRINT_DURATION / FPS

KICK_MIN_DISTANCE = KICK_MIN_DISTANCE_VALUE + PLAYER_RADIUS + BALL_RADIUS

UI_BUTTON_GAP = UI_BUTTON_DISTANCE + UI_BUTTON_HEIGHT
UI_BUTTON_LEFT = SCREEN_WIDTH / 2 - UI_BUTTON_WIDTH / 2
UI_BUTTON_TOP = SCREEN_HEIGHT / 2 - (UI_BUTTON_COUNT * UI_BUTTON_GAP - UI_BUTTON_GAP) / 2

GOAL_CENTER_GAP = GOAL_POST_BORDER_GAP + GOAL_WIDTH / 2

GK_STARTPOS_GAP = GOAL_POST_BORDER_GAP + GOAL_WIDTH + GK_STARTPOS_GOAL_GAP
GK_LEFT_STARTPOS = (GK_STARTPOS_GAP, SCREEN_HEIGHT / 2)
GK_RIGHT_STARTPOS = (SCREEN_WIDTH - GK_STARTPOS_GAP, SCREEN_HEIGHT / 2)